dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      name: EditorConfig Syntax Verification
      install:
        - npm install -g eclint
        - eclint --version
      script: eclint check
    - stage: lint
      name: Shell Script Syntax Verification
      script: make sh/lint
    - stage: lint
      name: JSON Lint/Format Verification
      script: make json/lint
    - stage: lint
      name: Terraform Lint/Format Verification
      install:
        - make terraform/install
        - make terraform-docs/install
      script:
        - make terraform/lint
        - make docs/lint
    - stage: lint
      language: python
      python: 3.6
      name: Python Lint/Format Verification
      install: pip install -r requirements/dev.txt
      script: make python/lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-null-validate-list-item
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-null-validate-list-item v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-null-validate-list-item/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: BUFFLFRF3z95U7M6aYLxYOI9Pr7qYicfVbAY7S9mr8vuX9xZYPY0gwaiaomzwKkfXR1j7ERIQPyq+m4c0YqY1inFra92jvgDL2XhXSmtWj0o7fUkEu8F4NtnO9GhDIK04qvBircVrQ5S/+hjA4N1fowOFUivx8qRnAcSFCuH6HIEvElZJsH5yUv6VY82xafACYkN2/wq92KLNbIS/izEGNEqaZNE15TFF27N+8C3n7bzwlVEjttr/+KHr43RvDRDmzBLhD8XPhyqhK3ZPovtBsSUjddeVhg6CadueMO22M1PLr926JqysLjLr2fOZpaQvidGeVDCWhfCRsdDDxSdv/jhW2Y09bZsvBDa9CFvw7MrOe0P1eijhu1wILY3V/iCUBErDRXmdlSjC53++x4TlhI64gWRxUx45mAAl3OztjaujoXOUjIr3wc0DwtrFmh5yFBDkmcCMeAzZwnQHG8cFrGlr0ss17AwTKh87PP2nzK0FW2EGb5Swqzz41MAOkKq8MpqDFvd7nrAADNb/MBoJbJardOjoZC1MRSHjJ6FVPCO5No5mM8HSTPglIXTZ4PlxHDjRtcqj+hCfuRCxwqQ8hKNwsqF4wMvK22lvy1ob4n6L4toT+hbRiL7g0GQHWGQmePShTcdpg801Q2OSY01pY2pB3/4urM+PiuMnkQTLIU=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-null-validate-list-item
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
