version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/valid_item"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
