name: Run test jobs
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: MetroStar/actions-workflows/.github/workflows/test.yml@00bdf2c02c2bb252dc7ba7f74816ac8359aa6693
